Add book, classroom and rental classes
elassis/OOP_library pull request #3
Opened 2021-12-15 21:24 UTC by elassis

# What I've Accomplished 🏁 
- Add Book, Classroom, and Rentals classes ✔️ 
- Add has many relations between classes ✔️ 
- Add belongs to relations between classes ✔️

2021-12-15 22:06 UTC, DeliceLydia requested changes
## Hi @elassis, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! my major highlights are:
- [ ] PR is professional
- [ ] README is descriptive


## Required Changes ♻️
_Check the comments under the review._




### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-15 22:06 UTC, DeliceLydia commented on book.rb
> +  attr_reader :rentals
- [x] I suggest that `rentals` be `attribute_accessor` as well to be able to access it and modify it

2021-12-15 22:06 UTC, DeliceLydia commented on rental.rb
> +  attr_reader :book, :person
- [x] `book` and `person` should be `attr_accessor` as well to access them and modify them

2021-12-15 22:06 UTC, DeliceLydia commented on rental.rb
> +  end
- [x] This method should be initialized with `date`, `book`, `person`

2021-12-15 22:06 UTC, DeliceLydia commented on person.rb
> +  end
- [x] To create a new `rental` you should send the person itself should be sent as a parameter to create the new rental achieving the 'has-many' associations. to create a new `rental` here should be created with `date`, `book`, and `person` itself

2021-12-15 22:06 UTC, DeliceLydia commented on book.rb
> +  end
- [x] `the book` itself should be sent as a parameter to create the new rental achieving the 'has-many' association. you can create a rental with `date`, `person` and `book` itself

2021-12-16 00:03 UTC, elisha2kyakpo1 approved these changes
Hi @elassis, 

Your project is complete!  There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 

Job well done implementing the requested changes🎉🎉🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 13:58 UTC, merged